Feature/control mode handler
kroshu/ros2_kuka_controllers pull request #3
Opened 2023-05-02 14:04 UTC by altex111

Control mode handler
A controller for control mode change in active mode

2023-05-03 14:52 UTC, VX792 requested changes

2023-05-03 14:52 UTC, VX792 commented on kuka_controllers/controller_plugins.xml
> +      This controller sets the control mode in real time to
cliffhanger!!

2023-05-03 14:52 UTC, VX792 commented on kuka_controllers/include/kuka_controllers/enum_converter.hpp
> +#ifndef UTILS_ENUM_CONVERTER_HPP_
this file is not needed currently, especially here. I made this so we could use enums more easily instead of type casting left and right. maybe in the future something like this will be useful but not now

2023-05-03 14:52 UTC, VX792 commented on kuka_controllers/src/control_mode_handler.cpp
> +      "Control mode unspecified, It is set to position control");
I don't think this is a good idea. The user should be forced to pass a valid control mode, because randomly choosing one is against the principle of least surprise.

2023-05-04 11:26 UTC, Svastits commented on kuka_controllers/src/control_mode_handler.cpp
> +      "Control mode unspecified, It is set to position control");
I think originally that was the idea, but as the controller_manager cannot properly handle the error from on_activate, this is used as a workaround.
However we should maybe think of another workaround, e.g. like throwing an exception

2023-05-25 13:30 UTC, altex111 commented on kuka_controllers/include/kuka_controllers/enum_converter.hpp
> +#ifndef UTILS_ENUM_CONVERTER_HPP_
deleted

2023-05-25 14:07 UTC, altex111 commented on kuka_controllers/src/robot_state_broadcaster.cpp
> +    interface_configuration_type::INDIVIDUAL};
roll back to 'NONE'

2023-05-25 14:09 UTC, altex111 commented on kuka_controllers/src/control_mode_handler.cpp
> +      "Control mode unspecified, It is set to position control");
Should we include this into this PR?

2023-05-25 14:10 UTC, altex111 commented on kuka_controllers/src/control_mode_handler.cpp
> +    [this](const std_msgs::msg::UInt32::SharedPtr msg) {
The original stays

2023-05-26 09:19 UTC, Svastits commented on kuka_controllers/src/control_mode_handler.cpp
> +      "Control mode unspecified, It is set to position control");
I think we can postpone this to at least be able to close this

2023-05-26 09:22 UTC, Svastits approved these changes

2023-05-26 09:32 UTC, VX792 approved these changes

2023-05-26 09:39 UTC, merged